name: build_fltk
description: 'Build FLTK library'

inputs:
  cmake_generator:
    description: 'Makefile generator used by CMake'
    required: true
    default: 'Unix Makefiles'
  shell_type:
    description: 'Shell type'
    required: true
    default: 'bash'

runs:
  using: "composite"

  steps:

    - name: FLTK
      run: |
        cd extern/fltk/
        pwd
        echo '### configure ###'
        mkdir build
        cd build
        cmake -G '${{inputs.cmake_generator}}' -S .. -B . -DFLTK_BUILD_FLUID=OFF -DFLTK_BUILD_TEST=OFF -DOPTION_BUILD_HTML_DOCUMENTATION=OFF -DOPTION_USE_CAIRO=OFF -DOPTION_USE_WAYLAND=OFF
        echo '### build ###'
        cmake --build . -j 8 --config Release
      shell: ${{inputs.shell_type}}

